### PR TITLE
profile-data: support delete of ProfileData

### PR DESCRIPTION
**Pull request by sam-github**
When ProfileData instance is deleted, also delete the profile file on
disk.

connected to strongloop-internal/scrum-nodeops#725

### CODE REVIEW

**Comment by sam-github** [comment]
@kraman PTAL, code is complete, but no tests. Does it look right to you?

It looks like I can test by modifying test-instance-profiling.js with a delete.

**Comment by kraman** [comment]
@sam-github AFAIK, deleteById won't populate the `ctx.where` instead it will probably populate `ctx.instance`. See: https://github.com/strongloop/strong-mesh-models/blob/master/server/models/server-service.js#L10

**Comment by sam-github** [comment]
@slnode test please

**Comment by sam-github** [comment]
@kraman PTAL, I am waiting for CI.

**Comment by sam-github** [comment]
@jtary PTAL

**Comment by kraman** [comment]
LGTM

**Comment by jtary** [comment]
LGTM

**Comment by sam-github** [comment]
Thanks for the reviews.

**Pull request merged**
