### PR TITLE
set ssh port when use http+ssh deploy via env

### PR DESCRIPTION
**Pull request by SemonCat**
I'm not use port 22 for ssh on my server.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by rmg** [comment]
@slnode ok to test

**Comment by SemonCat** [comment]
@rmg Can you help me checkout why fail?

I use same code from slc deploy.

Thanks.

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@SemonCat looks like a transient failure, rebuilding cleared it up :-)

This is missing a few pieces, but I'm going to merge this as-is and open another PR myself to fill in the remainder.

**Pull request merged**
