### PR TITLE
Persist set size (WIP)

### PR DESCRIPTION
**Pull request by sam-github**
I'd like to wait for after multiapp release to do this, I believe it may be related to, or at least occaisonally trigger, https://github.com/strongloop-internal/scrum-nodeops/issues/541

also, I need to fix the tests

depends on #45

### CODE REVIEW

**Comment by sam-github** [comment]
@slnode test please

**Comment by sam-github** [comment]
@slnode test please

**Comment by sam-github** [comment]
@slnode test please

**Comment by sam-github** [comment]
@slnode test please

**Comment by sam-github** [comment]
Passing locally, @kraman PTAL, as I wait for CI.

**Comment by kraman** [comment]
@sam-github LGTM

**Comment by sam-github** [comment]
@slnode test please

**Pull request merged**
