### PR TITLE
Model updates for strong-central

### PR DESCRIPTION
**Pull request by kraman**
connect to strongloop-internal/scrum-nodeops#675

### CODE REVIEW

**Comment by rmg** [comment]
The removal of `getPack` seems incomplete (didn't remove references from tests), but I'm not sure if it is a useful change or not. Won't we need something like those endpoints once central is storing some sort of "release" blob and it gets pushed/pulled around to different executors?

**Comment by kraman** [comment]
fixing tests

**Comment by kraman** [comment]
Executor will not be using the REST API exposed by mesh-models, in Central there will be a `/artifacts` endpoint to retrieve this file.

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
LGTM.

**Pull request merged**
