### PR TITLE
Dont change commit-info if not in notification

### PR DESCRIPTION
**Pull request by kraman**

### CODE REVIEW

**Comment by kraman** [comment]
See changes without white-space: https://github.com/strongloop/strong-mesh-models/pull/90/files?w=1

**Comment by sam-github** [comment]
LGTM, other than all the tests are broken, I'll kick the build.

**Comment by sam-github** [comment]
@slnode test please

**Comment by sam-github** [comment]
Was all green with a lint fix, and I needed it, so its landed.

**Pull request merged**
