### PR TITLE
Change process display name use instance id

### PR DESCRIPTION
**Pull request by kraman**
* Switch from [svc].[exec].[pid] to [svc].[inst].[pid] in CLI

### CODE REVIEW

**Comment by sam-github** [comment]
Shouldn't this change touch help text, somewhere?

Will also touch docs, /to @crandmck

**Comment by sam-github** [comment]
other than that, LGTM

**Comment by sam-github** [comment]
LGTM

**Comment by crandmck** [comment]
Thanks for the heads-up.  I updated https://docs.strongloop.com/display/NODE/sl-meshctl.

**Pull request merged**
